# path: ./config/models.yml
# title: AI Expert Definition with Self-Evolution Note
# description: 各エキスパートにコストと速度の指標を追加し、動的プランニングの判断材料を提供する。

# SELF-EVOLUTION: The 'enabled' flag of experts can be modified by the EvolutionService based on performance.
worker_experts:
  # --- General Purpose Experts ---
  jamba_default:
    name: "Jamba"
    description: "ユーザーとの対話、創造的な文章生成、タスク計画の立案など、幅広いコミュニケーションタスクを担当する汎用エキスパート。"
    expert_type: "jamba"
    model_env_key: "JAMBA_MODEL"
    chat_format: "chatml"
    system_prompt: "あなたは、誠実で優秀なAIアシスタントです。"
    enabled: true
    execution_strategy: "inline"
    cost_score: 2
    speed_score: 9

  greeter:
    name: "Greeter"
    description: "ユーザーとの挨拶や簡単なチャットなど、単純な対話に特化した軽量エキスパート。"
    expert_type: "jamba" # GreeterもJamba系の軽量モデルを想定
    model_env_key: "GREETER_MODEL"
    chat_format: "chatml"
    system_prompt: "あなたは、ユーザーの挨拶や簡単なチャットに、フレンドリーかつ簡潔に日本語で応答するAIアシスタントです。常に親切なトーンを心がけてください。"
    enabled: true
    execution_strategy: "inline"
    cost_score: 1
    speed_score: 10

  # --- Reasoning Experts ---
  hrm_default:
    name: "HRM"
    description: "複雑な論理パズル、計画立案、ステップバイステップの推論を得意とするエキスパート。システムの主要な思考エンジンとして機能する。"
    expert_type: "hrm"
    model_env_key: "HRM_MODEL"
    chat_format: "chatml"
    system_prompt: "You are a logical reasoner. Think step by step to solve the problem."
    enabled: true
    execution_strategy: "inline"
    cost_score: 6
    speed_score: 5

  reporter:
    name: "Reporter"
    description: "全エキスパートの成果を統合し、首尾一貫した最終報告書を作成するテクニカルライター。"
    expert_type: "hrm" # Reporterも論理的構成力が必要なためHRM系を想定
    model_env_key: "REPORTER_MODEL"
    chat_format: "chatml"
    system_prompt: "あなたは優秀なテクニカルライターです。提供された全タスクの結果を元に、ユーザーの元の要求に対する包括的で分かりやすい最終報告書を作成してください。"
    enabled: true
    execution_strategy: "inline"
    cost_score: 5
    speed_score: 6

  # --- Coding Experts ---
  transformer_default:
    name: "Transformer"
    description: "コーディング、プログラミング、具体的な関数の実装を得意とするエキスパート。"
    expert_type: "transformer"
    model_env_key: "TRANSFORMER_MODEL"
    chat_format: "gemma"
    system_prompt: "You are a helpful and intelligent assistant for coding. Provide clean, efficient, and well-commented code."
    enabled: true
    execution_strategy: "inline"
    cost_score: 5
    speed_score: 7

  # --- Specialized Experts ---
  liquids4_default:
    name: "LiquidS4"
    description: "長文の読解、要約、分析、そして長期的な文脈の記憶保持を得意とするエキスパート。"
    expert_type: "specialized"
    model_env_key: "LIQUIDS4_MODEL"
    chat_format: "llama-2"
    system_prompt: "You are an expert in summarizing and analyzing long texts. Provide a clear, concise, and logical summary."
    enabled: false # デフォルトでは無効
    execution_strategy: "inline"
    cost_score: 8
    speed_score: 3

  # --- Vision Experts ---
  visualizer_default:
    name: "Visualizer"
    description: "テキスト記述（プロンプト）から高品質な画像を生成する視覚化のエキスパート。"
    expert_type: "visualizer"
    model_id: "stabilityai/stable-diffusion-xl-base-1.0" # HuggingFace IDは直接指定
    chat_format: "diffusion"
    system_prompt: "You are a creative visualizer. Generate an image based on the user's prompt."
    enabled: true
    execution_strategy: "inline"
    cost_score: 9
    speed_score: 2
